language: node_js
node_js:
 - "node"
script:
  - echo "SCRIPT"
deploy:
  - provider: script
    skip_cleanup: true
    script: sh .travis/pu.sh
    on:
      branch: main
      tags: false
  - provider: npm
    email: antonio.fontainecorrea@gmail.com
    api_key: $NPM_TOKEN
    edge: true
    on:
      branch: main
